//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloudcre.Service.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cloudcre.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be no greater than 10 characters.
        /// </summary>
        public static string ValidationMsgCharacterRange10 {
            get {
                return ResourceManager.GetString("ValidationMsgCharacterRange10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be no greater than 100 characters.
        /// </summary>
        public static string ValidationMsgCharacterRange100 {
            get {
                return ResourceManager.GetString("ValidationMsgCharacterRange100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be no greater than 1000 characters.
        /// </summary>
        public static string ValidationMsgCharacterRange1000 {
            get {
                return ResourceManager.GetString("ValidationMsgCharacterRange1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be no greater than 20 characters.
        /// </summary>
        public static string ValidationMsgCharacterRange20 {
            get {
                return ResourceManager.GetString("ValidationMsgCharacterRange20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be no greater than 200 characters.
        /// </summary>
        public static string ValidationMsgCharacterRange200 {
            get {
                return ResourceManager.GetString("ValidationMsgCharacterRange200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be no greater than 50 characters.
        /// </summary>
        public static string ValidationMsgCharacterRange50 {
            get {
                return ResourceManager.GetString("ValidationMsgCharacterRange50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be in correct format, e.g. 55555 or 55555-5555.
        /// </summary>
        public static string ValidationMsgFormatZip {
            get {
                return ResourceManager.GetString("ValidationMsgFormatZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a percentage between 0 and 100.00.
        /// </summary>
        public static string ValidationMsgPercentageRange {
            get {
                return ResourceManager.GetString("ValidationMsgPercentageRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string ValidationMsgRequired {
            get {
                return ResourceManager.GetString("ValidationMsgRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date.
        /// </summary>
        public static string ValidationMsgValidDate {
            get {
                return ResourceManager.GetString("ValidationMsgValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number.
        /// </summary>
        public static string ValidationMsgValidNumber {
            get {
                return ResourceManager.GetString("ValidationMsgValidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid value.
        /// </summary>
        public static string ValidationMsgValidValue {
            get {
                return ResourceManager.GetString("ValidationMsgValidValue", resourceCulture);
            }
        }
    }
}
